# Description: Configuration file for ATAC-seq pipeline

# Sample accession list and metadata
sra_acc_list: 'resources/SRR_Acc_List.txt'
sample_metadata: 'resources/SraRunTable.txt'

Reads:
    - 1
    - 2

# genome
genome: '/scratch/jbreda/genome/mm10/Mus_musculus.GRCm38.dna.primary_assembly.fa'

# dirs
tmp_dir: 'tmp'
input_dir: 'resources/fastq'
fastqc_dir: 'results/fastqc'
trimmomatic_dir: 'results/trimmomatic'
mapping_dir: 'results/mapping'
peak_dir: 'results/peaks'

# trimmomatic
adapter: '../Trimmomatic/adapters/NexteraPE-PE.fa:2:30:10:2:True'
leading: 3
trailing: 3
window: '4:15'
minlen: 36

# peak calling
hmmratac:
    window: 5000000

TISSUE:
    - Abdominalfat
    - Adrenalgland
    - Bladder
    - Brownfat
    - Cerebellum
    - Cerebrum
    - Heart
    - Kidney
    - Largeintestine
    - Liver
    - Lung
    - Mesentericfat
    - Ovary
    - Pancreas
    - Skeletalmuscle
    - Smallintestine
    - Spleen
    - Stomach
    - Thymus
    - Uterus
SEX:
    - male
    - female